github:
  user_or_org: Mirebeau
channels:
  targets:
  - [mirebeau, main]
travis:
  secure:
    BINSTAR_TOKEN: ZKsPltEiCB0xSm6KdsJfjOqGkiRnRxgJY6/M48WK/GW7I+XqM/OdeWzZZDP+riM34/oeiVkl5HbG2ytApjjtG9S4TZVDmnrGxQNToPYZCjlBvnjaAJ1j5V/bylVnLA3u0XrfKu7GCtD8juaLpFNIDlg2vyd0fbTcOr2FXnZS54c9beNotsR/p/5z/GEtZlfKKXfVPD4NWFcW3hqIF1UfxxB1NbMmy3UOkdOxHljprEBbI8zC+2SYB+P4ODf0Q8/GiNGbVtlYMxFJ1twBw0jZzECdnqgVDxlp6qvIzS9XHBBB0Finz9A4U8Qr7w9AMu3Z2gu9YrzJ5ADcKRCp8EuWgSpv+F2pb73jNAyDE0XALrW162d0rxQyP5LC6wlN0+yc2HDa7RWRIMUU25A9hvoCL6FBzxVJBDKs80QPw+nzJmhqsllM+Oso+t0mZyTifTneJYH0jdRnGv9ke6+urzDTzj9mX7pTzS1BDgIrE88eIIwA7KeSwsQxGY4yCtVfXw8dhhqcTYfOUSu5bOU9IaEeJ6x9+c8Y2BgXdKDZuqc39RH+5AZmhakHvCBtDtmnIovzhx4Xl3SePXYZIMH1cn9z6zHhU+o1CSnYaU2aMMpqSGfWHdHbIwvmtsjAli81a7ywuyp1NYhNUpb+aDPlqWiuimsyoLBICJv57MKbclKL/6o=
appveyor:
  secure:
    BINSTAR_TOKEN: YpZmS7TlI5W/NZbTuI3p+u9L+R9q+GjBwEw9QFc6iP5K+F2JHrllJ9gXuwrox/1I
