github:
  user_or_org: Mirebeau
channels:
  targets:
  - [mirebeau, main]
appveyor:
  secure:
    BINSTAR_TOKEN: YpZmS7TlI5W/NZbTuI3p+u9L+R9q+GjBwEw9QFc6iP5K+F2JHrllJ9gXuwrox/1I
travis:
  secure:
    BINSTAR_TOKEN: pDnCRBaqcesHpz0kO8IWcwCj3ZohSjR24GL5k06B8cbcpPiwJAlxGyO6Wbg1jxxCLqabHsGzhkf80rynRbeE8tKJ9tljONx9B0fg2sX8B5hcBsi/9ze0wgYyIZM99DprEQZb/aIvfJh/u+hO/Btt2O9bkXBGvXLiGb93htJmKC5VuSQt/VyUt97FZtuJg13LRLWM1df9RhBlhu6cqUw6NrBjMrPLzRrkR1Qdj13XZhCOTycjbKgIowfSPPF0/Ik9hFtPFqUSMT/wXTcJuhOPm+9thuZhyerdpX1SPULP6FR8sUQozPC7fDnd7ajXm+cSFIYUFVxDz/zWVB5ibjsG28Gy6YdZ3fTfg0TnUqd9XE8Kdr+k0wOXeBF/3Flphsqn2PKfMx5XTSiU6AYgKH8Kmfqmd9yAfRDfis0E0LVNaDk2psjFjTi1Y2OMoQvxZ6p7iSTExlbXKVKQBDCSE/ilZ1MMZOYZxsPbi7E6K5Etf85rDSr8X4L9Dkm4o+kcP1sqvFxpXTnsKl8DcOuCugaeEc9TzcZ7uLlIjpQvEVFMFW5kMyJlXVsJCmclpq6HVe5SA2igw0SXoM/rMoE1ohD3Krp2IPwr5d4SKNvJwEGcR7VRIhj5BnvHICpHUmh9iLVU+Lp6wguwoLGVT1RyfVirliU7Y57DlANXqJzWD+1bQ8g=
